name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "
            # Navigate to project directory
            cd /home/ubuntu/bharatccrest
            
            # Pull latest changes (if repo already exists)
            git pull origin main || git clone https://github.com/yourusername/your-repo.git .
            
            # Ensure permissions (optional)
            sudo chown -R ubuntu:ubuntu /home/ubuntu/bharatccrest
            
            # Restart Nginx
            sudo systemctl restart nginx
          "
