name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "
            # Ensure directory exists
            mkdir -p /home/ubuntu/bharatccrest
            cd /home/ubuntu/bharatccrest
            
            # Clean existing files (optional)
            # rm -rf ./* 2>/dev/null || true
            
            # Clone/pull logic
            if [ -d .git ]; then
              git pull origin main
            else
              git clone https://${{ secrets.GH_TOKEN }}@github.com/yourusername/your-repo.git .
            fi
            
            # Fix permissions
            sudo chown -R ubuntu:ubuntu /home/ubuntu/bharatccrest
            
            # Restart Nginx
            sudo systemctl restart nginx
          "
