name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
        env:
          EC2_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_IP }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            set -e
            cd /home/ubuntu/bharatccrest || git clone git@github.com:07himanshu20/bharatccrest.git /home/ubuntu/bharatccrest
            cd /home/ubuntu/bharatccrest
            git pull origin main
            sudo chown -R ubuntu:ubuntu /home/ubuntu/bharatccrest
            sudo systemctl restart nginx
          EOF
