name: Deploy to EC2

on:
  push:
    branches:
      - main   # or your branch name

jobs:
  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/bharatccrest
          git pull origin main
          sudo systemctl reload nginx
