name: Deploy to EC2

on:
  push:
    branches:
      - main   # or your branch name

jobs:
  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -T ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # Navigate to your project directory
          cd /home/ubuntu/bharatccrest
          
          # Pull the latest code from GitHub
          git pull origin main
          
          # Add build steps if necessary (e.g., npm install, npm run build)
          # npm install
          # npm run build
          
          # Reload nginx after deployment
          sudo systemctl reload nginx
        EOF
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}

